language: python

matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - wget https://raw.githubusercontent.com/y-yu/install-tex-travis/master/install-tex.sh
        - wget https://raw.githubusercontent.com/y-yu/install-tex-travis/master/tlmgr.sh
        - chmod +x install-tex.sh tlmgr.sh
        - choco install python
        - python -m pip install --upgrade pip
        env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
cache:
  directories:
    - $HOME/texlive
    - $HOME/.texlive
    - $HOME/texmf







sudo: false



# command to install dependencies
install:
    - pip3 install --upgrade pip
  - . ./install-tex.sh
  - ./tlmgr.sh install collection-langjapanese
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest .
#  - pylint *.py #- .pylintrc - can
